version: "3.8"
services:
  mysql-container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Redhat123#
      MYSQL_DATABASE: cafe
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysql-container
    ports:
      - "9090:8080"

